In [1]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
import json
from census import Census

In [2]:
# Census API key
from courtCensusKey import censusKey

In [3]:
complete_url='https://api.census.gov/data/timeseries/intltrade/exports/hs'+\
            '?get=DISTRICT,DIST_NAME,ALL_VAL_MO,ALL_VAL_YR,E_COMMODITY_SDESC'+\
            '&E_COMMODITY=3926201010'+\
            '&YEAR=2020'+\
            '&MONTH=*'

In [4]:
response=requests.get(complete_url)
response

In [5]:
pd.DataFrame(response.json())

,0,1,2,3,4,5,6,7
0,DISTRICT,DIST_NAME,ALL_VAL_MO,ALL_VAL_YR,E_COMMODITY_SDESC,E_COMMODITY,YEAR,MONTH
1,-,TOTAL FOR ALL DISTRICTS,1355169,1355169,"GLOVES,SEAMLESS,SURGICAL & MEDICAL,OF PLASTIC",3926201010,2020,01
2,-,TOTAL FOR ALL DISTRICTS,5125594,6480763,"GLOVES,SEAMLESS,SURGICAL & MEDICAL,OF PLASTIC",3926201010,2020,02
3,-,TOTAL FOR ALL DISTRICTS,2408079,8888842,"GLOVES,SEAMLESS,SURGICAL & MEDICAL,OF PLASTIC",3926201010,2020,03
4,-,TOTAL FOR ALL DISTRICTS,1245130,10133972,"GLOVES,SEAMLESS,SURGICAL & MEDICAL,OF PLASTIC",3926201010,2020,04
...,...,...,...,...,...,...,...,...
286,70,LOW VALUE,27824,369655,"GLOVES,SEAMLESS,SURGICAL & MEDICAL,OF PLASTIC",3926201010,2020,09
287,70,LOW VALUE,34215,403870,"GLOVES,SEAMLESS,SURGICAL & MEDICAL,OF PLASTIC",3926201010,2020,10
288,70,LOW VALUE,29864,433734,"GLOVES,SEAMLESS,SURGICAL & MEDICAL,OF PLASTIC",3926201010,2020,11
289,80,MAIL SHIPMENTS,2618,2618,"GLOVES,SEAMLESS,SURGICAL & MEDICAL,OF PLASTIC",3926201010,2020,10
290,80,MAIL SHIPMENTS,0,2618,"GLOVES,SEAMLESS,SURGICAL & MEDICAL,OF PLASTIC",3926201010,2020,11

In [6]:
#Setting variables 
year='2020'
month='*'
cols='DISTRICT,DIST_NAME,ALL_VAL_MO,ALL_VAL_YR,E_COMMODITY_SDESC'

In [7]:
#Base URL 
base_url = 'https://api.census.gov/data/timeseries/intltrade/exports/hs'

complete_url = f'{base_url}?get={cols}&YEAR={year}&MONTH={month}'


hts_list=['2926100000','4002510000','4002590000','2836500000','4002110000','3904100000']
df_list=[]

for each_hts in hts_list:
    hts_code=each_hts
    query_params={
        'get': 'CTY_CODE,CTY_NAME,DF,DISTRICT,DIST_NAME,ALL_VAL_MO,ALL_VAL_YR,E_COMMODITY_SDESC',
        'E_COMMODITY': hts_code,
        'YEAR': '2020',
        'MONTH': "*"
    }
    max_response=requests.get(base_url, params=query_params)
    #print(max_response.json())
    df_list.append(max_response.json()[1:])
#print(df_list)

In [8]:
productList = []
for product in df_list:
    productList += product

In [9]:
exportData2020 = pd.DataFrame(productList, columns=max_response.json()[0])
exportData2020

,CTY_CODE,CTY_NAME,DF,DISTRICT,DIST_NAME,ALL_VAL_MO,ALL_VAL_YR,E_COMMODITY_SDESC,E_COMMODITY,YEAR,MONTH
0,-,TOTAL FOR ALL COUNTRIES,1,-,TOTAL FOR ALL DISTRICTS,64081017,64081017,ACRYLONITRILE,2926100000,2020,01
1,0020,NAFTA,-,07,"OGDENSBURG, NY",215368,215368,ACRYLONITRILE,2926100000,2020,01
2,0022,OECD,-,07,"OGDENSBURG, NY",215368,215368,ACRYLONITRILE,2926100000,2020,01
3,0023,NATO,-,07,"OGDENSBURG, NY",215368,215368,ACRYLONITRILE,2926100000,2020,01
4,0026,APEC,-,07,"OGDENSBURG, NY",215368,215368,ACRYLONITRILE,2926100000,2020,01
...,...,...,...,...,...,...,...,...,...,...,...
51038,0022,OECD,1,70,LOW VALUE,12281,165189,"POLYVINYL CHLORIDE,NOT MIXED WITH ANY OTH SUBS...",3904100000,2020,11
51039,0023,NATO,1,70,LOW VALUE,12281,165189,"POLYVINYL CHLORIDE,NOT MIXED WITH ANY OTH SUBS...",3904100000,2020,11
51040,0026,APEC,1,70,LOW VALUE,12281,165189,"POLYVINYL CHLORIDE,NOT MIXED WITH ANY OTH SUBS...",3904100000,2020,11
51041,1220,CANADA,1,70,LOW VALUE,12281,165189,"POLYVINYL CHLORIDE,NOT MIXED WITH ANY OTH SUBS...",3904100000,2020,11
51042,1XXX,NORTH AMERICA,1,70,LOW VALUE,12281,165189,"POLYVINYL CHLORIDE,NOT MIXED WITH ANY OTH SUBS...",3904100000,2020,11

In [10]:
exportData2020['E_COMMODITY_SDESC'].unique()

array(['ACRYLONITRILE', 'LATEX OF ACRYLONITRILE-BUTADIENE RUBBER (NBR)',
       'ACRYLONITRILE-BUTADIENE RUBBER, EXC LATEX, NESOI',
       'CALCIUM CARBONATE', 'LATEX OF (SBR); (XSBR)',
       'POLYVINYL CHLORIDE,NOT MIXED WITH ANY OTH SUBSTANC'], dtype=object)

In [11]:
# Rename columns
exportData2020 = exportData2020.rename(columns={"CTY_CODE": "COUNTRY_CODE", "CTY_NAME": "COUNTRY_NAME", "DF": "DOMESTIC_FOREIGN_CODE", "DIST_NAME": "DISTRICT_NAME", "ALL_VAL_MO": "ALL_VALUES_MONTH", "ALL_VAL_YR": "ALL_VALUES_YEAR", "E_COMMODITY_SDESC": "COMMODITY_DESCRIPTION", "E_COMMODITY": "COMMODITY"})
exportData2020

,COUNTRY_CODE,COUNTRY_NAME,DOMESTIC_FOREIGN_CODE,DISTRICT,DISTRICT_NAME,ALL_VALUES_MONTH,ALL_VALUES_YEAR,COMMODITY_DESCRIPTION,COMMODITY,YEAR,MONTH
0,-,TOTAL FOR ALL COUNTRIES,1,-,TOTAL FOR ALL DISTRICTS,64081017,64081017,ACRYLONITRILE,2926100000,2020,01
1,0020,NAFTA,-,07,"OGDENSBURG, NY",215368,215368,ACRYLONITRILE,2926100000,2020,01
2,0022,OECD,-,07,"OGDENSBURG, NY",215368,215368,ACRYLONITRILE,2926100000,2020,01
3,0023,NATO,-,07,"OGDENSBURG, NY",215368,215368,ACRYLONITRILE,2926100000,2020,01
4,0026,APEC,-,07,"OGDENSBURG, NY",215368,215368,ACRYLONITRILE,2926100000,2020,01
...,...,...,...,...,...,...,...,...,...,...,...
51038,0022,OECD,1,70,LOW VALUE,12281,165189,"POLYVINYL CHLORIDE,NOT MIXED WITH ANY OTH SUBS...",3904100000,2020,11
51039,0023,NATO,1,70,LOW VALUE,12281,165189,"POLYVINYL CHLORIDE,NOT MIXED WITH ANY OTH SUBS...",3904100000,2020,11
51040,0026,APEC,1,70,LOW VALUE,12281,165189,"POLYVINYL CHLORIDE,NOT MIXED WITH ANY OTH SUBS...",3904100000,2020,11
51041,1220,CANADA,1,70,LOW VALUE,12281,165189,"POLYVINYL CHLORIDE,NOT MIXED WITH ANY OTH SUBS...",3904100000,2020,11
51042,1XXX,NORTH AMERICA,1,70,LOW VALUE,12281,165189,"POLYVINYL CHLORIDE,NOT MIXED WITH ANY OTH SUBS...",3904100000,2020,11

In [12]:
# Save as a csv
# Using encoding="utf-8" to avoid issues later
exportData2020.to_csv("Resources/exportData2020.csv", encoding="utf-8", index=False)

In [13]:
#Convert to county data to dataframe, perform some basic operations
#county_df=pd.DataFrame(countyData[1:], columns=countyData[0]).\
#rename(columns={"GEO_ID": "GEOID", "GEONAME": "CountyST"})
#county_df['fips']=county_df.state+county_df.county
#county_df.set_index('fips',inplace=True)
#county_df.drop(columns=['state','county'],inplace=True)
#county_df[['County','State']] = county_df.CountyST.str.split(",",expand=True)
#county_df.dropna(how="any", inplace=True)
#county_df