In [1]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from census import Census
from us import states

# Census API key
from courtCensusKey import censusKey

In [2]:
#Import Data
#from https://simplemaps.com/data/us-zips

data = pd.read_csv("Resources/international_lat_lng.csv")
data

                       COUNTRY_NAME      LAT       LNG             LAT,LNG
0                    EUROPEAN UNION  54.5400   25.1900        54.54, 25.19
1             PACIFIC RIM COUNTIRES  12.8797  121.7740    12.8797, 121.774
2                             NAFTA  47.1164 -101.2996  47.1164, -101.2996
3   TWENTY LATIN AMERICAN REPUBLICS  -4.4420  -61.3269    -4.442, -61.3269
4                              OECD  28.8566    2.3522     28.8566, 2.3522
5                              NATO  50.8503    4.3517     50.8503, 4.3517
6                             LAFTA -38.4161  -63.6167  -38.4161, -63.6167
7                         EURO AREA  48.6690   19.6990      48.669, 19.699
8                              APEC   1.3521  103.8198    1.3521, 103.8198
9                             ASEAN  -6.2088  106.8456   -6.2088, 106.8456
10                    NORTH AMERICA  54.5260 -105.2551   54.526, -105.2551
11                           MEXICO  23.6345 -102.5528  23.6345, -102.5528
12                           FRANCE  46.2276    2.2137     46.2276, 2.2137
13                      SWITZERLAND  46.8182    8.2275     46.8182, 8.2275
14                           EUROPE  54.5260   15.2551     54.526, 15.2551
15                          VIETNAM  14.0583  108.2772   14.0583, 108.2772
16                         MALAYSIA   4.2105  101.9758    4.2105, 101.9758
17                            CHINA  35.8617  104.1954   35.8617, 104.1954
18                             ASIA  34.0479  100.6197   34.0479, 100.6197
19                           TAIWAN  23.6978  120.9605   23.6978, 120.9605
20                           CANADA  56.1304 -106.3468  56.1304, -106.3468
21                          AUSTRIA  47.5162   14.5501    47.5162, 14.5501
22                            INDIA  20.5937   78.9629    20.5937, 78.9629
23                          GERMANY  52.5200   13.4050       52.52, 13.405
24                         CAFTA-DR   9.7489   83.7534     9.7489, 83.7534
25               DOMINICAN REPUBLIC  18.7357  -70.1627   18.7357, -70.1627
26                  CENTRAL AMERICA  12.7690  -85.6024    12.769, -85.6024
27                          ESTONIA  58.5953   25.0136    58.5953, 25.0136
28                           BRAZIL -14.2350  -51.9253   -14.235, -51.9253
29                    SOUTH AMERICA  -8.7832  -55.4916   -8.7832, -55.4916
30                            ITALY  41.8719   12.5674    41.8719, 12.5674
31                   UNITED KINGDOM  55.3781   -3.4350     55.3781, -3.435
32                        HONG KONG  22.3193  114.1694   22.3193, 114.1694
33                        SRI LANKA   7.8731   80.7718     7.8731, 80.7718
34                         THAILAND  15.8700  100.9925     15.87, 100.9925
35                        INDONESIA   0.7893  113.9213    0.7893, 113.9213